### ISSUE TITLE
Create more templates

### ISSUE THREAD

**Issue by matteobruni** [tsparticles/404-templates#1]
Any new 404 template is welcome.

Only templates using [tsParticles](https://particles.js.org) for particles animations will be accepted.

**Comment by priyanshu688** [comment]
I can work on this issue if you assign it to me.. Please brief me what I exactly need to do.

**Comment by priyanshu688** [comment]
@matteobruni

**Comment by matteobruni** [comment]
@priyanshu688 this is a creative task, you can submit a reusable 404 page template, the only requirement is using tsParticles for particles animations, like the other templates in the repository

**Comment by priyanshu688** [comment]
@matteobruni that means I have to make a reusable 404 page template using tsParticles

**Comment by priyanshu688** [comment]
@matteobruni Please review this PR- https://github.com/tsparticles/404-templates/pull/3

**Comment by Shiyasmohd** [comment]
can i work on this?i if yes please do assign me

**Comment by drishtipeshwani** [comment]
Hello, can I work on this issue

**Comment by matteobruni** [comment]
> Hello, can I work on this issue

Yes sure

**Comment by oneamanish** [comment]
see my pull req.

**Comment by Amirhossein-Veysi** [comment]
Hi, I like to contribute on this project, Please assign me :)

**Comment by Amirhossein-Veysi** [comment]
Hi, I like to contribute to this repository, Please assign me :)

**Comment by prathambagadiya** [comment]
i would like to work on this please assign to me

**Comment by matteobruni** [comment]
> i would like to work on this please assign to me

Assigned
