### ISSUE TITLE
Adding new 404 error template

### ISSUE THREAD

**Issue by Ahasasjain** [tsparticles/404-templates#103]
### Details

Adding a new 404 template in the project please assign me this issue under hacktoberFest 2023.

<details open>
<summary>Checklist</summary>

- [X] ``new_template/404.html`` ✅ Commit [`719de93`](https://github.com/tsparticles/404-templates/commit/719de93bb390d8634d40247b3c5188d4d6e993a8)
- [X] ``new_template/css/404.css`` ✅ Commit [`964d730`](https://github.com/tsparticles/404-templates/commit/964d730d33c0255a1465c4edb516ecadcf909e5d)
- [X] ``new_template/js/404.js`` ✅ Commit [`00424f2`](https://github.com/tsparticles/404-templates/commit/00424f288fa9792525de8d4a7c2017340b9baf0a)
- [X] ``data/pages.json`` ✅ Commit [`d4b45a2`](https://github.com/tsparticles/404-templates/commit/d4b45a2647d3a505d5b7e212955ad98402ef6a49)
</details>

**Comment by matteobruni** [comment]
There is already an issue for that. Please use that
