### ISSUE TITLE
Feature Request: Want to add two new theme: "galaxy" & "starwars"

### ISSUE THREAD

**Issue by Khushalsarode** [tsparticles/404-templates#155]
### Contact Details

khushalsarode.in@gmail.com

### What is your request?

- have created an two new 404 theme using tsparticles
- galaxy: galaxy related theme with asteroid and space void saying you are lost!
- starwars: 404 wars! force leaved you! 
![galaxy](https://github.com/user-attachments/assets/b4071cac-c612-4e17-899a-dc300308ec8f)
![starwars](https://github.com/user-attachments/assets/68b6fe81-792a-4a5c-b4ff-a60b35e34298)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Khushalsarode** [comment]
@matteobruni do let me know!

**Comment by matteobruni** [comment]
If you have something to submit, please open a PR.
