### ISSUE TITLE
New 404 Templates

### ISSUE THREAD

**Issue by matteobruni** [tsparticles/404-templates#18]
Any new 404 template is welcome.

**Only templates using [tsParticles](https://particles.js.org) for particle animations will be accepted**. If it's not using tsParticles, the PR will be closed and marked as invalid. If more than one is invalid, all the invalid PR will be marked as **spam**.

Requirements for posting a template:

- Add all files in a folder, the template **MUST** work.
- Add a screenshot in the *__screenshots* (https://github.com/tsparticles/404-templates/tree/main/__screenshots) folder
- Add the template to `data/pages.json` (https://github.com/tsparticles/404-templates/blob/main/data/pages.json) file. You can copy an existing one updating all the informations.

All the *Pull Requests* require this format. Any wrong Pull Request will be marked as invalid and closed.

**If I receive multiple invalid Pull Requests from the same user, I'll mark them as spam.**

**Comment by aswinikalyan30** [comment]
can I take this up?

**Comment by matteobruni** [comment]
> can I take this up?

Anyone can work on that, it’s not a single user task.

**Comment by depimomo** [comment]
I have submitted one template, is it okay to submit more?

**Comment by matteobruni** [comment]
> I have submitted one template, is it okay to submit more?

Yeah sure. It's not a problem to push more than one template in a single PR either.

**Comment by matteobruni** [comment]
I'm closing this issue, it's a duplicate of #18 without all the requirements.

**Comment by anmolrajsoni15** [comment]
Sorry for the inconvenience but can I know where was I wrong.

**Comment by matteobruni** [comment]
> Any new 404 template is welcome.
> 
> Only templates using [tsParticles](https://particles.js.org) for particle animations will be accepted. If it's not using tsParticles, the PR will be marked as invalid.
> 
> Requirements for posting a template:
> 
> * Add all files in a folder, the template **MUST** work.
> * Add a screenshot in the ___screenshots_ (https://github.com/tsparticles/404-templates/tree/main/__screenshots) folder
> * Add the template to `data/pages.json` (https://github.com/tsparticles/404-templates/blob/main/data/pages.json) file. You can copy an existing one updating all the information.
> 
> All the _Pull Requests_ require this format. Any wrong Pull Request will be marked as invalid and closed.
> 
> **If I receive multiple invalid Pull Requests from the same user, I'll mark them as spam.**

These instructions already explains everything. Reading them is not optional.

Using [tsParticles](https://github.com/matteobruni/tsparticles) is **mandatory** in all 404 templates commited here. In your PR it wasn't used, as you can see here: https://github.com/anmolrajsoni15/404-templates/blob/49a4c8e0b2042b97ef84636a0d3e1c3b99273766/human/index.html

After that, all the previews uses a png image, you used a gif. It could be a minor issue, but I prefer having a standard to follow.

And lastly, the `data/pages.json` wasn't updated. That is the file responsible for showing the template in the index page.

**Comment by anmolrajsoni15** [comment]
I am very sorry for that @matteobruni. Please give me a chance by assigning the issue to work on it again . This time I will make sure that all the requirements are fulfilled.
Thank You

**Comment by matteobruni** [comment]
> I am very sorry for that @matteobruni. Please give me a chance by assigning the issue to work on it again . This time I will make sure that all the requirements are fulfilled.
> Thank You

As I said in the other task, assigning tasks is not mandatory for PR. You can submit one anyway. I prefer to keep this task without assignments. The assignments are limited to 10 users, and everyone can submit a template.

**Comment by sumitbaroniya** [comment]
Please assign me this issue. I would like to contribute in it.

**Comment by matteobruni** [comment]
> Please assign me this issue. I would like to contribute in it.

As said in previous messages, I prefer to not assign the issue. It's an open issue for everyone, so I keep it unassigned. It's not important for the Hacktoberfest

**Comment by anmolrajsoni15** [comment]
Hello @matteobruni. I have again tried to make a new page template. But this time before generating PR , , I would like you to review this image.
And if it is ok then can I generate the PR ?
![burning](https://user-images.githubusercontent.com/93241741/194382534-e5abc921-7c0b-4121-8637-8d5543e5efb7.png)

**Comment by matteobruni** [comment]
> 

Looks good, there’s a fire 404 but it’s very different
