### ISSUE TITLE
Adding styling to the website.

### ISSUE THREAD

**Issue by YashBawa** [tsparticles/404-templates#19]
A basic background coloring to the website and some gradients to the header to make it look eye-catchy .

**Comment by YashBawa** [comment]
Hey @matteobruni  can u please assign me this issue under hacktoberfest Label .

**Comment by YashBawa** [comment]
Thank you @matteobruni for assigning me the issue . can u please add the Hacktoberfest label .

**Comment by sumitbaroniya** [comment]
Please assign me this issue. I would like to contribute in it.
