### ISSUE TITLE
I want to add tailwindcss 404 page

### ISSUE THREAD

**Issue by Alidhuniya** [tsparticles/404-templates#21]
assign it under hacktober fest

**Comment by abhishekpatil4** [comment]
@Alidhuniya Can I work on this? I worked on tailwind CSS
I'm a full stack developer (HTML CSS Javascript + MERN Stack - MongoDB Express Js React Js Node Js)

**Comment by matteobruni** [comment]
Closing this issue, the requirements are explained in #18. Read there for contributing.
