### ISSUE TITLE
add new interface 

### ISSUE THREAD

**Issue by shreyashkr17** [tsparticles/404-templates#23]
![image](https://user-images.githubusercontent.com/97216718/193458422-f20e105a-5fb5-42c1-8ea1-5de562d6a704.png)

i want to change the interface of this page so that it looks more attractive @matteobruni

**Comment by matteobruni** [comment]
Ok, be careful, there’s already a PR and an issue about that. #20 #19

**Comment by shreyashkr17** [comment]
can you add the tag of the hacktoberfest and type of issue

**Comment by matteobruni** [comment]
It’s not necessary for the Hacktoberfest, it counts only the PRs

**Comment by abhishekpatil4** [comment]
@shreyashkr17 Can I work on this? I'm a full stack developer (HTML CSS Javascript + MERN Stack - MongoDB Express Js React Js Node Js)

**Comment by shreyashkr17** [comment]
bro i have started on this ... find another issues

**Comment by matteobruni** [comment]
> i have started on this ... find another issues

Please, stay calm. As I said there was already another issue of @YashBawa with a reviewed PR. You can all work on this with different changes.

**Comment by matteobruni** [comment]
I will close this, since there's already an other issue about that. It's better to have one. Use #19 instead.
