### ISSUE TITLE
Addition of New 404 Template

### ISSUE THREAD

**Issue by Ritika122001** [tsparticles/404-templates#33]
Kindly assign the issue!!
Thank You.

**Comment by Ritika122001** [comment]
Hey @matteobruni. Could you please assign this issue under the Hacktoberfest label?

**Comment by matteobruni** [comment]
> Hey @matteobruni. Could you please assign this issue under the Hacktoberfest label?

It's not mandatory for Hacktoberfest, it counts only PRs, but no problem anyway

**Comment by ShrutiJ-01** [comment]
I'd like to raise a PR for a new 404 template. Could you please assign it to me as well?

**Comment by anmolrajsoni15** [comment]
I have an amazing animated page design.
@matteobruni I would really appreciate it if you could assign me this issue so that can I can start contributing to this repo and generate a successfull PR.
Thank you and have a great Hacktoberfest ['22!]

**Comment by anmolrajsoni15** [comment]
Hello @matteobruni I am ready with my design. Please assign this issue so that I can generate a successful PR.
Thank You

**Comment by anmolrajsoni15** [comment]
Thank You @matteobruni for assigning the issue to me. I have successfully generated the PR. Kindly accept it.

**Comment by matteobruni** [comment]
I'm closing this issue, it's a duplicate of #18 without all the requirements.
