### ISSUE TITLE
Add separate element for the Github Link.

### ISSUE THREAD

**Issue by Blurry-Brush** [tsparticles/404-templates#39]
The GitHub link is not visible to the public. Hence a separate element like : 
![image](https://user-images.githubusercontent.com/89006056/193885335-9ce6d735-f33d-49ed-99c6-0f08b7432bab.png)
in the top-right area would be really beneficial and readable.

**Comment by Blurry-Brush** [comment]
sorry to bother you @matteobruni, but can you hacktoberfest label?

**Comment by matteobruni** [comment]
@Blurry-Brush yeah, but remember that only PR counts, assigning or labelling issues is not necessary for the hacktoberfest.

**Comment by Blurry-Brush** [comment]
Oh, I didn't know that, thank you!

**Comment by Blurry-Brush** [comment]
Hello @matteobruni, I have implemented the feature but when creating the pull request, I am getting 'can't merge automatically'. What should I do?

**Comment by matteobruni** [comment]
> Hello @matteobruni, I have implemented the feature but when creating the pull request, I am getting 'can't merge automatically'. What should I do?

You have to merge from this repository `main` branch to yours

**Comment by Blurry-Brush** [comment]
@matteobruni please review the PR.
