### ISSUE TITLE
Want to align buttons to the center and add a github icon for better UX.

### ISSUE THREAD

**Issue by DeveloperAshish8** [tsparticles/404-templates#53]
The "view" button is currently desplaying to the left.

***Before***
![Screenshot (7)](https://user-images.githubusercontent.com/90233808/194694054-7499e2eb-5154-4043-a13f-a064636c9b28.png)

***After***
![Screenshot (6)](https://user-images.githubusercontent.com/90233808/194694062-8b4944c6-335a-4723-9c3b-e24aeab76dd6.png)

**Comment by DeveloperAshish8** [comment]
Please assign this issue to me under hacktoberfest.

**Comment by matteobruni** [comment]
Sorry but I don't like the button centered, do you have other ideas?
