### ISSUE TITLE
Feature Request: Add footer

### ISSUE THREAD

**Issue by radhika141** [tsparticles/404-templates#68]
### Contact Details

khetanradhika14@gmail.com

### What is your request?

Please assign me this issue, I want to add footer to the website showing features such as copyright claim, etc.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by deepaksuthar40128** [comment]
Can you assign it to me?

**Comment by deepaksuthar40128** [comment]
can you add hacktoberfest tag here?

**Comment by matteobruni** [comment]
It’s useless tagging issues with hacktoberfest

**Comment by deepaksuthar40128** [comment]
they consider my PR without tag?

**Comment by matteobruni** [comment]
Yes, the repository is tagged
