### ISSUE TITLE
[Hacktoberfest 2023] New 404 Templates

### ISSUE THREAD

**Issue by matteobruni** [tsparticles/404-templates#97]
## Any new 404 template is welcome.

**Only templates using [tsParticles](https://particles.js.org) for particle animations will be accepted**. If it's not using tsParticles, the PR will be closed and marked as invalid. If more than one is invalid, all the invalid PR will be marked as **spam**.

## Requirements for posting a template

- Add all files in a folder, the template **MUST** work. Please split HTML, CSS and JS code to different files, see other templates as a reference.
- Add a screenshot in the *__screenshots* (https://github.com/tsparticles/404-templates/tree/main/__screenshots) folder
- Add the template to `data/pages.json` (https://github.com/tsparticles/404-templates/blob/main/data/pages.json) file. You can copy an existing one updating all the informations.
- Add the Google Analytics Code (below)
- Run `npm install` and `npm run prettier` to format the files

## Google Analytics 4 Code

```
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-1752YPLP7H"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-1752YPLP7H');
</script>
```

## Spam check

All the *Pull Requests* require this format. Any wrong Pull Request will be marked as invalid and closed.

**If I receive multiple invalid Pull Requests from the same user, I'll mark them as spam.**

**Comment by Ahasasjain** [comment]
Hii can I work on this issue?

**Comment by matteobruni** [comment]
> Hii can I work on this issue?

Sure

**Comment by matteobruni** [comment]
Closing this, Hacktoberfest 2023 ended.
